name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
  vipcs:
      name: VIPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: VIPCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 'WordPress-VIP-Go'
  tenupcs:
      name: 10upCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            enable_warnings: true
            excludes: './tests/ ./includes/admin/post-meta.php'
  localconfig: 
      name: Local Config
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            use_local_config: 'true'
            extra_args: "--extensions=php"
  changed_lines:
      name: Changed Lines only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            only_changed_lines: 'true'
  changed_files:
      name: Changed Files only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            only_changed_files: 'true'
  custom_standard:
      name: Custom standard repo
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard_repo: 'https://github.com/10up/phpcs-composer'
            repo_branch: 'trunk'
  excludes:
      name: With excludes
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            excludes: './tests/ ./includes/admin/post-meta.php'

  includes:
      name: With paths only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            paths: './includes/admin/post-meta.php ./includes/admin/settings.php'
  phpcs1:
      name: WPCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@develop
  vipcs1:
      name: VIPCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: VIPCS check
          uses: 10up/wpcs-action@develop
          with:
            standard: 'WordPress-VIP-Go'
  tenupcs1:
      name: 10upCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@develop
          with:
            standard: 10up-Default
            enable_warnings: true
  localconfig1: 
      name: WPCS check1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@develop
          with:
            use_local_config: 'true'
            extra_args: "--extensions=php"
