name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: iamdharmesh/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
  vipcs:
      name: VIPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: VIPCS check
          uses: iamdharmesh/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 'WordPress-VIP-Go'
  tenupcs:
      name: 10upCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: iamdharmesh/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            enable_warnings: true
  localconfig: 
      name: WPCS check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: iamdharmesh/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            use_local_config: 'true'
            extra_args: "--extensions=php"
  phpcs1:
      name: WPCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@develop
  vipcs1:
      name: VIPCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: VIPCS check
          uses: 10up/wpcs-action@develop
          with:
            standard: 'WordPress-VIP-Go'
  tenupcs1:
      name: 10upCS1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@develop
          with:
            standard: 10up-Default
            enable_warnings: true
  localconfig1: 
      name: WPCS check1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: 10upCS check
          uses: 10up/wpcs-action@develop
          with:
            use_local_config: 'true'
            extra_args: "--extensions=php"
