name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: Default CS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
  vipcs:
      name: VIPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 'WordPress-VIP-Go'
  tenupcs:
      name: 10upCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            enable_warnings: true
            excludes: './tests/'
  localconfig: 
      name: Use Local Config
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            use_local_config: 'true'
            extra_args: "--extensions=php"
  changed_lines:
      name: Changed Lines only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            only_changed_lines: 'true'
  changed_lines1:
      name: Changed Lines only1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: 10up/wpcs-action@stable
          with:
            standard: 10up-Default
            only_changed_lines: 'true'
  changed_files:
      name: Changed Files only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            only_changed_files: 'true'
  custom_standard:
      name: Custom standard repo
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard_repo: 'https://github.com/10up/phpcs-composer'
            repo_branch: 'trunk'
  excludes:
      name: With excludes
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            excludes: './tests/,./includes/admin/post-meta.php'
  includes:
      name: With paths only
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: 10up/wpcs-action@fix/35-upgrade-wordpress-coding-standards-to-3.1
          with:
            standard: 10up-Default
            paths: './includes/admin/post-meta.php ./includes/admin/settings.php'
